import { Base64 } from 'js-base64';
import trimStart from 'lodash/trimStart';
import trim from 'lodash/trim';
import result from 'lodash/result';
import partial from 'lodash/partial';
import last from 'lodash/last';
import initial from 'lodash/initial';
import {
  APIError,
  basename,
  generateContentKey,
  getAllResponses,
  localForage,
  parseContentKey,
  readFileMetadata,
  requestWithBackoff,
  unsentRequest,
  CMS_BRANCH_PREFIX,
  branchFromContentKey,
  isCMSLabel,
  labelToStatus,
  statusToLabel,
  DEFAULT_PR_BODY,
  MERGE_COMMIT_MESSAGE,
  PreviewState,
} from 'decap-cms-lib-util';

import type {
  DataFile,
  PersistOptions,
  AssetProxy,
  ApiRequest,
  FetchError,
} from 'decap-cms-lib-util';
import type { Semaphore } from 'semaphore';
import type {
  FilesResponse,
  GitGetBlobResponse,
  GitGetTreeResponse,
  GiteaUser,
  GiteaRepository,
  ReposListCommitsResponse,
  GiteaPullRequest,
  GiteaBranch,
  GiteaLabel,
  GiteaChangedFile,
  GiteaCompareResponse,
  GiteaCompareCommit,
  GiteaCombinedStatus,
} from './types';

export const API_NAME = 'Gitea';

export const MOCK_PULL_REQUEST = -1;

type TreeEntry = {
  path: string;
  mode: string;
  type: string;
  sha: string | null;
};

export interface Config {
  apiRoot?: string;
  token?: string;
  branch?: string;
  repo?: string;
  originRepo?: string;
  cmsLabelPrefix?: string;
  useOpenAuthoring?: boolean;
  initialWorkflowStatus?: string;
}

enum FileOperation {
  CREATE = 'create',
  DELETE = 'delete',
  UPDATE = 'update',
}

export interface ChangeFileOperation {
  content?: string;
  from_path?: string;
  path: string;
  operation: FileOperation;
  sha?: string;
}

interface MetaDataObjects {
  entry: { path: string; sha: string };
  files: MediaFile[];
}

export interface Metadata {
  type: string;
  objects: MetaDataObjects;
  branch: string;
  status: string;
  collection: string;
  commitMessage: string;
  version?: string;
  user: string;
  title?: string;
  description?: string;
  timeStamp: string;
}

export interface BlobArgs {
  sha: string;
  repoURL: string;
  parseText: boolean;
}

type Param = string | number | undefined;

export type Options = RequestInit & {
  params?: Record<string, Param | Record<string, Param> | string[]>;
};

type MediaFile = {
  sha: string;
  path: string;
};

export default class API {
  apiRoot: string;
  token: string;
  branch: string;
  repo: string;
  originRepo: string;
  repoOwner: string;
  repoName: string;
  originRepoOwner: string;
  originRepoName: string;
  repoURL: string;
  originRepoURL: string;
  cmsLabelPrefix: string;
  useOpenAuthoring: boolean;
  initialWorkflowStatus: string;

  _userPromise?: Promise<GiteaUser>;
  _metadataSemaphore?: Semaphore;

  commitAuthor?: {};

  constructor(config: Config) {
    this.apiRoot = config.apiRoot || 'https://try.gitea.io/api/v1';
    this.token = config.token || '';
    this.branch = config.branch || 'master';
    this.repo = config.repo || '';
    this.originRepo = config.originRepo || this.repo;
    this.repoURL = `/repos/${this.repo}`;
    this.originRepoURL = `/repos/${this.originRepo}`;
    this.cmsLabelPrefix = config.cmsLabelPrefix || '';
    this.useOpenAuthoring = config.useOpenAuthoring || false;
    this.initialWorkflowStatus = config.initialWorkflowStatus || 'draft';

    const [repoParts, originRepoParts] = [this.repo.split('/'), this.originRepo.split('/')];
    this.repoOwner = repoParts[0];
    this.repoName = repoParts[1];

    this.originRepoOwner = originRepoParts[0];
    this.originRepoName = originRepoParts[1];
  }

  static DEFAULT_COMMIT_MESSAGE = 'Automatically generated by Static CMS';

  user(): Promise<{ full_name: string; login: string; avatar_url: string }> {
    if (!this._userPromise) {
      this._userPromise = this.getUser();
    }
    return this._userPromise;
  }

  getUser() {
    return this.request('/user') as Promise<GiteaUser>;
  }

  async hasWriteAccess() {
    try {
      const result: GiteaRepository = await this.request(this.repoURL);
      // update config repoOwner to avoid case sensitivity issues with Gitea
      this.repoOwner = result.owner.login;
      return result.permissions.push;
    } catch (error) {
      console.error('Problem fetching repo data from Gitea');
      throw error;
    }
  }

  reset() {
    // no op
  }

  requestHeaders(headers = {}) {
    const baseHeader: Record<string, string> = {
      'Content-Type': 'application/json; charset=utf-8',
      ...headers,
    };

    if (this.token) {
      baseHeader.Authorization = `token ${this.token}`;
      return Promise.resolve(baseHeader);
    }

    return Promise.resolve(baseHeader);
  }

  async parseJsonResponse(response: Response) {
    const json = await response.json();
    if (!response.ok) {
      return Promise.reject(json);
    }
    return json;
  }

  urlFor(path: string, options: Options) {
    const params = [];
    if (options.params) {
      for (const key in options.params) {
        params.push(`${key}=${encodeURIComponent(options.params[key] as string)}`);
      }
    }
    if (params.length) {
      path += `?${params.join('&')}`;
    }
    return this.apiRoot + path;
  }

  parseResponse(response: Response) {
    const contentType = response.headers.get('Content-Type');
    if (contentType && contentType.match(/json/)) {
      return this.parseJsonResponse(response);
    }
    const textPromise = response.text().then(text => {
      if (!response.ok) {
        return Promise.reject(text);
      }
      return text;
    });
    return textPromise;
  }

  handleRequestError(error: FetchError, responseStatus: number) {
    throw new APIError(error.message, responseStatus, API_NAME);
  }

  buildRequest(req: ApiRequest) {
    return req;
  }

  async request(
    path: string,
    options: Options = {},
    parser = (response: Response) => this.parseResponse(response),
  ) {
    options = { cache: 'no-cache', ...options };
    const headers = await this.requestHeaders(options.headers || {});
    const url = this.urlFor(path, options);
    let responseStatus = 500;

    try {
      const req = unsentRequest.fromFetchArguments(url, {
        ...options,
        headers,
      }) as unknown as ApiRequest;
      const response = await requestWithBackoff(this, req);
      responseStatus = response.status;
      const parsedResponse = await parser(response);
      return parsedResponse;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (error: any) {
      return this.handleRequestError(error, responseStatus);
    }
  }

  nextUrlProcessor() {
    return (url: string) => url;
  }

  async requestAllPages<T>(url: string, options: Options = {}) {
    options = { cache: 'no-cache', ...options };
    const headers = await this.requestHeaders(options.headers || {});
    const processedURL = this.urlFor(url, options);
    const allResponses = await getAllResponses(
      processedURL,
      { ...options, headers },
      'next',
      this.nextUrlProcessor(),
    );
    const pages: T[][] = await Promise.all(
      allResponses.map((res: Response) => this.parseResponse(res)),
    );
    return ([] as T[]).concat(...pages);
  }

  generateContentKey(collectionName: string, slug: string) {
    const contentKey = generateContentKey(collectionName, slug);
    if (!this.useOpenAuthoring) {
      return contentKey;
    }
    // In open authoring, include the repo in the content key
    return `${this.repo}/${contentKey}`;
  }

  parseContentKey(contentKey: string) {
    if (!this.useOpenAuthoring) {
      return parseContentKey(contentKey);
    }
    // In open authoring, strip the repo prefix before parsing
    return parseContentKey(contentKey.slice(this.repo.length + 1));
  }

  async readFile(
    path: string,
    sha?: string | null,
    {
      branch = this.branch,
      repoURL = this.repoURL,
      parseText = true,
    }: {
      branch?: string;
      repoURL?: string;
      parseText?: boolean;
    } = {},
  ) {
    if (!sha) {
      sha = await this.getFileSha(path, { repoURL, branch });
    }
    const content = await this.fetchBlobContent({ sha: sha as string, repoURL, parseText });
    return content;
  }

  async readFileMetadata(path: string, sha: string | null | undefined) {
    const fetchFileMetadata = async () => {
      try {
        const result: ReposListCommitsResponse = await this.request(
          `${this.originRepoURL}/commits`,
          {
            params: { path, sha: this.branch, stat: 'false' },
          },
        );
        const { commit } = result[0];
        return {
          author: commit.author.name || commit.author.email,
          updatedOn: commit.author.date,
        };
      } catch (e) {
        return { author: '', updatedOn: '' };
      }
    };
    const fileMetadata = await readFileMetadata(sha, fetchFileMetadata, localForage);
    return fileMetadata;
  }

  async fetchBlobContent({ sha, repoURL, parseText }: BlobArgs) {
    const result: GitGetBlobResponse = await this.request(`${repoURL}/git/blobs/${sha}`, {
      cache: 'force-cache',
    });

    if (parseText) {
      // treat content as a utf-8 string
      const content = Base64.decode(result.content);
      return content;
    } else {
      // treat content as binary and convert to blob
      const content = Base64.atob(result.content);
      const byteArray = new Uint8Array(content.length);
      for (let i = 0; i < content.length; i++) {
        byteArray[i] = content.charCodeAt(i);
      }
      const blob = new Blob([byteArray]);
      return blob;
    }
  }

  async listFiles(
    path: string,
    { repoURL = this.repoURL, branch = this.branch, depth = 1 } = {},
    folderSupport?: boolean,
  ): Promise<{ type: string; id: string; name: string; path: string; size: number }[]> {
    const folder = trim(path, '/');
    try {
      const result: GitGetTreeResponse = await this.request(
        `${repoURL}/git/trees/${branch}:${encodeURIComponent(folder)}`,
        {
          // Gitea API supports recursive=1 for getting the entire recursive tree
          // or omitting it to get the non-recursive tree
          params: depth > 1 ? { recursive: 1 } : {},
        },
      );
      return (
        result.tree
          // filter only files and/or folders up to the required depth
          .filter(
            file =>
              (!folderSupport ? file.type === 'blob' : true) &&
              decodeURIComponent(file.path).split('/').length <= depth,
          )
          .map(file => ({
            type: file.type,
            id: file.sha,
            name: basename(file.path),
            path: `${folder}/${file.path}`,
            size: file.size!,
          }))
      );
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      if (err && err.status === 404) {
        console.info('[StaticCMS] This 404 was expected and handled appropriately.');
        return [];
      } else {
        throw err;
      }
    }
  }

  async persistFiles(dataFiles: DataFile[], mediaFiles: AssetProxy[], options: PersistOptions) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const files: (DataFile | AssetProxy)[] = mediaFiles.concat(dataFiles as any);
    const operations = await this.getChangeFileOperations(files, this.branch);
    return this.changeFiles(operations, options);
  }

  async changeFiles(operations: ChangeFileOperation[], options: PersistOptions) {
    return (await this.request(`${this.repoURL}/contents`, {
      method: 'POST',
      body: JSON.stringify({
        branch: this.branch,
        files: operations,
        message: options.commitMessage,
      }),
    })) as FilesResponse;
  }

  async getChangeFileOperations(files: { path: string; newPath?: string }[], branch: string) {
    const items: ChangeFileOperation[] = await Promise.all(
      files.map(async file => {
        const content = await result(
          file,
          'toBase64',
          partial(this.toBase64, (file as DataFile).raw),
        );
        let sha;
        let operation;
        let from_path;
        let path = trimStart(file.path, '/');
        try {
          sha = await this.getFileSha(file.path, { branch });
          operation = FileOperation.UPDATE;
          from_path = file.newPath && path;
          path = file.newPath ? trimStart(file.newPath, '/') : path;
        } catch {
          sha = undefined;
          operation = FileOperation.CREATE;
        }

        return {
          operation,
          content,
          path,
          from_path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    return items;
  }

  async getFileSha(path: string, { repoURL = this.repoURL, branch = this.branch } = {}) {
    /**
     * We need to request the tree first to get the SHA. We use extended SHA-1
     * syntax (<rev>:<path>) to get a blob from a tree without having to recurse
     * through the tree.
     */

    const pathArray = path.split('/');
    const filename = last(pathArray);
    const directory = initial(pathArray).join('/');
    const fileDataPath = encodeURIComponent(directory);
    const fileDataURL = `${repoURL}/git/trees/${branch}:${fileDataPath}`;

    const result: GitGetTreeResponse = await this.request(fileDataURL);
    const file = result.tree.find(file => file.path === filename);
    if (file) {
      return file.sha;
    } else {
      throw new APIError('Not Found', 404, API_NAME);
    }
  }

  async deleteFiles(paths: string[], message: string) {
    const operations: ChangeFileOperation[] = await Promise.all(
      paths.map(async path => {
        const sha = await this.getFileSha(path);

        return {
          operation: FileOperation.DELETE,
          path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    this.changeFiles(operations, { commitMessage: message });
  }

  toBase64(str: string) {
    return Promise.resolve(Base64.encode(str));
  }

  async getBranch(branchName: string): Promise<GiteaBranch> {
    return this.request(`${this.repoURL}/branches/${encodeURIComponent(branchName)}`);
  }

  async getDefaultBranch(): Promise<GiteaBranch> {
    return this.getBranch(this.branch);
  }

  async createBranch(
    branchName: string,
    oldBranchName: string = this.branch,
  ): Promise<GiteaBranch> {
    return this.request(`${this.repoURL}/branches`, {
      method: 'POST',
      body: JSON.stringify({
        new_branch_name: branchName,
        old_ref_name: oldBranchName,
      }),
    });
  }

  async deleteBranch(branchName: string): Promise<void> {
    await this.request(`${this.repoURL}/branches/${encodeURIComponent(branchName)}`, {
      method: 'DELETE',
    });
  }

  async getPullRequests(
    state: 'open' | 'closed' | 'all' = 'open',
    head?: string,
  ): Promise<GiteaPullRequest[]> {
    const params: Record<string, string> = { state };
    if (head) {
      params.head = head;
    }
    return this.request(`${this.originRepoURL}/pulls`, { params });
  }

  /**
   * Get the head reference for a branch (used for cross-fork PRs)
   */
  async getHeadReference(head: string): Promise<string> {
    return `${this.repoOwner}:${head}`;
  }

  /**
   * Get PR for open authoring - maps PR state to workflow status
   */
  async getOpenAuthoringPullRequest(
    branch: string,
    pullRequests: GiteaPullRequest[],
  ): Promise<GiteaPullRequest> {
    // In open authoring, we can't use labels since contributors don't have permission
    // Status is derived from PR state: no PR = draft, open PR = pending_review
    const branchData = await this.getBranch(branch).catch(() => {
      throw new APIError('content is not under editorial workflow', 404, API_NAME);
    });

    // Filter PRs by head SHA to find matching one
    const pullRequest = pullRequests.find(pr => pr.head.sha === branchData.commit.id);

    if (!pullRequest) {
      // No PR found - return mock PR with draft status
      return {
        head: { sha: branchData.commit.id },
        number: MOCK_PULL_REQUEST,
        labels: [{ name: statusToLabel(this.initialWorkflowStatus, this.cmsLabelPrefix) }],
        state: 'open',
      } as unknown as GiteaPullRequest;
    }

    // PR exists - set status based on PR state
    const statusLabel =
      pullRequest.state === 'closed'
        ? statusToLabel(this.initialWorkflowStatus, this.cmsLabelPrefix)
        : statusToLabel('pending_review', this.cmsLabelPrefix);

    // Filter out CMS labels and add the appropriate one
    pullRequest.labels = pullRequest.labels.filter(
      l => !isCMSLabel(l.name, this.cmsLabelPrefix),
    );
    pullRequest.labels.push({ name: statusLabel } as GiteaLabel);

    return pullRequest;
  }

  async getBranchPullRequest(branchName: string): Promise<GiteaPullRequest> {
    if (this.useOpenAuthoring) {
      // Open authoring: get all PRs (open and closed) and use special handling
      const headRef = await this.getHeadReference(branchName);
      const allPRs = await this.getPullRequests('all', headRef);
      return this.getOpenAuthoringPullRequest(branchName, allPRs);
    }

    // Standard mode: look for open PRs with CMS labels
    const pullRequests = await this.getPullRequests('open', `${this.repoOwner}:${branchName}`);
    if (pullRequests.length > 0) {
      return pullRequests[0];
    }
    // Check closed PRs as fallback
    const closedPRs = await this.getPullRequests('closed', `${this.repoOwner}:${branchName}`);
    if (closedPRs.length > 0) {
      return closedPRs[0];
    }
    throw new APIError('Pull request not found', 404, API_NAME);
  }

  async createPR(
    title: string,
    head: string,
    body: string = DEFAULT_PR_BODY,
  ): Promise<GiteaPullRequest> {
    return this.request(`${this.originRepoURL}/pulls`, {
      method: 'POST',
      body: JSON.stringify({
        title,
        head,
        base: this.branch,
        body,
      }),
    });
  }

  async updatePR(number: number, state: 'open' | 'closed'): Promise<GiteaPullRequest> {
    return this.request(`${this.originRepoURL}/pulls/${number}`, {
      method: 'PATCH',
      body: JSON.stringify({ state }),
    });
  }

  async closePR(number: number): Promise<GiteaPullRequest> {
    console.log('%c Closing PR', 'line-height: 30px;text-align: center;font-weight: bold');
    return this.updatePR(number, 'closed');
  }

  async openPR(number: number): Promise<GiteaPullRequest> {
    console.log('%c Re-opening PR', 'line-height: 30px;text-align: center;font-weight: bold');
    return this.updatePR(number, 'open');
  }

  async mergePR(pullRequest: GiteaPullRequest): Promise<void> {
    try {
      await this.request(`${this.originRepoURL}/pulls/${pullRequest.number}/merge`, {
        method: 'POST',
        body: JSON.stringify({
          do: 'merge',
          merge_message_field: MERGE_COMMIT_MESSAGE,
        }),
      });
    } catch (error) {
      // Gitea returns 405 when merge is not possible (conflicts, etc.)
      // or 409 for conflict errors
      if (error instanceof APIError && (error.status === 405 || error.status === 409)) {
        return this.forceMergePR(pullRequest);
      }
      throw error;
    }
  }

  /**
   * Force merge a PR by recreating its changes on top of the base branch.
   * Used when normal merge fails due to conflicts.
   */
  async forceMergePR(pullRequest: GiteaPullRequest): Promise<void> {
    console.log(
      '%c Automatic merge not possible - Forcing merge.',
      'line-height: 30px;text-align: center;font-weight: bold',
    );

    // Get the files changed in this PR
    const files = await this.getPullRequestFiles(pullRequest.number);

    // Build a commit message listing all files
    let commitMessage = 'Automatically generated. Merged on Decap CMS\n\nForce merge of:';
    for (const file of files) {
      commitMessage += `\n* "${file.filename}"`;
    }

    // Get the current default branch
    const defaultBranch = await this.getDefaultBranch();
    const baseSha = defaultBranch.commit.id;

    // For each file in the PR, get its content from the PR head and apply to base
    const treeUpdates: { path: string; sha: string | null }[] = [];

    for (const file of files) {
      if (file.status === 'removed') {
        // File was deleted
        treeUpdates.push({ path: file.filename, sha: null });
      } else {
        // File was added or modified - get its SHA from the PR head
        try {
          const sha = await this.getFileSha(file.filename, {
            branch: pullRequest.head.sha,
            repoURL: this.repoURL,
          });
          treeUpdates.push({ path: file.filename, sha });
        } catch (e) {
          console.warn(`Could not get SHA for file ${file.filename} during force merge`, e);
        }
      }

      // Handle renamed files - delete the old path
      if (file.status === 'renamed' && file.previous_filename) {
        treeUpdates.push({ path: file.previous_filename, sha: null });
      }
    }

    // Create a new tree with the changes applied to the base
    const changeTree = await this.updateTree(baseSha, treeUpdates);

    // Create a commit
    const commit = await this.commit(commitMessage, changeTree);

    // Update the default branch to point to the new commit
    // Note: This requires direct branch update since we're bypassing the PR merge
    await this.request(`${this.repoURL}/git/refs/heads/${encodeURIComponent(this.branch)}`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha }),
    });

    // Close the PR since we've manually merged it
    await this.closePR(pullRequest.number);
  }

  async getPullRequestFiles(number: number): Promise<GiteaChangedFile[]> {
    return this.request(`${this.originRepoURL}/pulls/${number}/files`);
  }

  async updatePullRequestLabels(number: number, labels: number[]): Promise<GiteaLabel[]> {
    return this.request(`${this.originRepoURL}/issues/${number}/labels`, {
      method: 'PUT',
      body: JSON.stringify({ labels }),
    });
  }

  async getLabels(): Promise<GiteaLabel[]> {
    return this.request(`${this.originRepoURL}/labels`);
  }

  async createLabel(name: string, color = '0052cc'): Promise<GiteaLabel> {
    return this.request(`${this.originRepoURL}/labels`, {
      method: 'POST',
      body: JSON.stringify({ name, color }),
    });
  }

  async getOrCreateLabel(name: string): Promise<GiteaLabel> {
    const labels = await this.getLabels();
    const existing = labels.find(l => l.name === name);
    if (existing) {
      return existing;
    }
    return this.createLabel(name);
  }

  async setPullRequestStatus(pullRequest: GiteaPullRequest, status: string): Promise<void> {
    const newLabel = statusToLabel(status, this.cmsLabelPrefix);

    // Get or create the new status label
    const label = await this.getOrCreateLabel(newLabel);

    // Get current labels and filter out old CMS labels
    const currentLabels = pullRequest.labels
      .filter(l => !isCMSLabel(l.name, this.cmsLabelPrefix))
      .map(l => l.id);

    // Add the new status label
    await this.updatePullRequestLabels(pullRequest.number, [...currentLabels, label.id]);
  }

  /**
   * Filter open authoring branches - remove merged ones
   */
  filterOpenAuthoringBranches = async (
    branch: string,
  ): Promise<{ branch: string; filter: boolean }> => {
    try {
      const pullRequest = await this.getBranchPullRequest(branch);
      const { state, merged_at: mergedAt } = pullRequest;

      if (pullRequest.number !== MOCK_PULL_REQUEST && state === 'closed' && mergedAt) {
        // PR was merged, delete branch
        await this.deleteBranch(branch);
        return { branch, filter: false };
      }
      return { branch, filter: true };
    } catch (e) {
      return { branch, filter: false };
    }
  };

  /**
   * Get all CMS branches in the fork for open authoring
   */
  async getOpenAuthoringBranches(): Promise<{ ref: string }[]> {
    try {
      // Fetch branches matching pattern: cms/${repo}/*
      const branches: GiteaBranch[] = await this.requestAllPages(
        `${this.repoURL}/branches`,
      );

      // Filter to only CMS branches for this repo
      const prefix = `${CMS_BRANCH_PREFIX}/${this.repo}/`;
      return branches
        .filter(b => b.name.startsWith(prefix))
        .map(b => ({ ref: `refs/heads/${b.name}` }));
    } catch (e) {
      return [];
    }
  }

  async listUnpublishedBranches(): Promise<string[]> {
    console.log(
      '%c Checking for Unpublished entries',
      'line-height: 30px;text-align: center;font-weight: bold',
    );

    let branches: string[];

    if (this.useOpenAuthoring) {
      // Open authoring: branches can exist without a PR
      const cmsBranches = await this.getOpenAuthoringBranches();
      branches = cmsBranches.map(b => b.ref.slice('refs/heads/'.length));

      // Filter out merged branches
      const branchesWithFilter = await Promise.all(
        branches.map(b => this.filterOpenAuthoringBranches(b)),
      );
      branches = branchesWithFilter.filter(b => b.filter).map(b => b.branch);
    } else {
      // Standard mode: get branches from open PRs
      const pullRequests = await this.getPullRequests('open');
      branches = pullRequests
        .filter(pr => pr.head.ref.startsWith(`${CMS_BRANCH_PREFIX}/`))
        .map(pr => pr.head.ref);
    }

    return branches;
  }

  /**
   * Retrieve commit statuses for a given collection/slug.
   * Used for deploy preview links.
   */
  async getStatuses(
    collectionName: string,
    slug: string,
  ): Promise<{ context: string; target_url: string; state: PreviewState }[]> {
    const contentKey = this.generateContentKey(collectionName, slug);
    const branch = branchFromContentKey(contentKey);
    const pullRequest = await this.getBranchPullRequest(branch);
    const sha = pullRequest.head.sha;

    // Gitea uses /repos/{owner}/{repo}/commits/{sha}/status for combined status
    const resp: GiteaCombinedStatus = await this.request(
      `${this.originRepoURL}/commits/${sha}/status`,
    );

    return (resp.statuses || []).map(s => ({
      context: s.context,
      target_url: s.target_url || '',
      state: s.status === 'success' ? PreviewState.Success : PreviewState.Other,
    }));
  }

  async retrieveUnpublishedEntryData(contentKey: string) {
    const branch = branchFromContentKey(contentKey);
    const pullRequest = await this.getBranchPullRequest(branch);
    const files = await this.getPullRequestFiles(pullRequest.number);

    const statusLabel = pullRequest.labels.find(l => isCMSLabel(l.name, this.cmsLabelPrefix));
    const status = statusLabel ? labelToStatus(statusLabel.name, this.cmsLabelPrefix) : 'draft';

    const { collection, slug } = this.parseContentKey(contentKey);

    return {
      collection,
      slug,
      status,
      diffs: files.map(file => ({
        path: file.filename,
        newFile: file.status === 'added',
        id: '', // SHA not directly available from files endpoint
      })),
      updatedAt: pullRequest.updated_at,
      pullRequestAuthor: pullRequest.user.login,
    };
  }

  async updateUnpublishedEntryStatus(collection: string, slug: string, newStatus: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);
    const pullRequest = await this.getBranchPullRequest(branch);

    if (!this.useOpenAuthoring) {
      // Standard mode: use labels for status tracking
      const currentState = pullRequest.state;

      // Handle status transitions that require PR state changes
      if (currentState === 'open' && newStatus === 'draft') {
        // When moving to draft, close the PR (makes it less visible)
        await this.closePR(pullRequest.number);
        // Fetch updated PR to set status on
        const updatedPR = await this.getBranchPullRequest(branch);
        await this.setPullRequestStatus(updatedPR, newStatus);
      } else if (currentState === 'closed' && newStatus === 'pending_review') {
        // When moving to pending_review from a closed PR, reopen it
        await this.openPR(pullRequest.number);
        // Fetch updated PR to set status on
        const updatedPR = await this.getBranchPullRequest(branch);
        await this.setPullRequestStatus(updatedPR, newStatus);
      } else {
        // For other transitions, just update the status label
        await this.setPullRequestStatus(pullRequest, newStatus);
      }
    } else {
      // Open authoring mode: status is managed via PR state, not labels
      if (newStatus === 'pending_publish') {
        throw new Error('Open Authoring entries may not be set to the status "pending_publish".');
      }

      if (pullRequest.number !== MOCK_PULL_REQUEST) {
        // Real PR exists
        const { state } = pullRequest;

        if (state === 'open' && newStatus === 'draft') {
          // Close PR to mark as draft
          await this.closePR(pullRequest.number);
        }
        if (state === 'closed' && newStatus === 'pending_review') {
          // Reopen PR to mark as pending_review
          await this.openPR(pullRequest.number);
        }
      } else if (newStatus === 'pending_review') {
        // No PR yet, but user wants to submit for review - create PR
        const headRef = await this.getHeadReference(branch);
        const diff = await this.getDifferences(this.branch, headRef);
        const title =
          diff.commits[0]?.commit?.message || API.DEFAULT_COMMIT_MESSAGE;
        await this.createPR(title, branch);
      }
    }
  }

  async deleteUnpublishedEntry(collection: string, slug: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    try {
      const pullRequest = await this.getBranchPullRequest(branch);
      await this.closePR(pullRequest.number);
    } catch (e) {
      // PR might not exist, continue to delete branch
    }

    await this.deleteBranch(branch);
  }

  async publishUnpublishedEntry(collection: string, slug: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    const pullRequest = await this.getBranchPullRequest(branch);
    await this.mergePR(pullRequest);
    await this.deleteBranch(branch);
  }

  async editorialWorkflowGit(
    files: { path: string; newPath?: string }[],
    slug: string,
    collection: string,
    options: PersistOptions,
  ) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);
    const unpublished = options.unpublished || false;

    if (!unpublished) {
      // New entry - create branch and potentially PR
      await this.createBranch(branch, this.branch);

      // Persist files to the branch
      const operations = await this.getChangeFileOperationsForBranch(files, branch);
      await this.changeFilesOnBranch(operations, options, branch);

      if (this.useOpenAuthoring) {
        // Open authoring: only create branch, PR created on status change to pending_review
        // No label setting since contributors don't have permission
      } else {
        // Standard mode: create PR and set status
        const pr = await this.createPR(options.commitMessage, branch);
        const status = options.status || this.initialWorkflowStatus;
        await this.setPullRequestStatus(pr, status);
      }
    } else {
      // Entry is already on editorial workflow - rebase and update
      try {
        // Get the differences to identify media files that should be removed
        const { files: diffFiles } = await this.getDifferences(this.branch, branch);

        // Identify media files that are no longer in the entry
        const mediaFilesList = files.map(f => trimStart(f.path, '/'));
        const mediaFilesToRemove: { path: string; sha: null }[] = [];

        for (const diff of diffFiles) {
          // Check if it's a binary/media file (no text content typically)
          const isBinaryLike =
            diff.filename.match(/\.(jpg|jpeg|png|gif|svg|webp|ico|pdf|mp3|mp4|webm|ogg)$/i) !==
            null;
          if (isBinaryLike && !mediaFilesList.includes(diff.filename)) {
            mediaFilesToRemove.push({ path: diff.filename, sha: null });
          }
        }

        // Rebase the branch before applying new changes
        const rebasedHead = await this.rebaseBranch(branch);

        // Upload blobs for the files
        const uploadedFiles: { path: string; sha: string }[] = [];
        for (const file of files) {
          const uploaded = await this.uploadBlob(file as { raw?: string; toBase64?: () => Promise<string> });
          uploadedFiles.push({
            path: trimStart(file.newPath || file.path, '/'),
            sha: uploaded.sha as string,
          });
        }

        // Combine with media files to remove
        const allFiles = [
          ...mediaFilesToRemove,
          ...uploadedFiles,
        ];

        // Create new tree with changes
        const changeTree = await this.updateTree(rebasedHead.sha, allFiles);

        // Create commit
        const commit = await this.commit(options.commitMessage, changeTree);

        // Force update the branch
        await this.patchBranch(branch, commit.sha, { force: true });
      } catch (error) {
        console.error('Error in editorial workflow update with rebase:', error);
        // Fallback to simple update without rebase
        const operations = await this.getChangeFileOperationsForBranch(files, branch);
        await this.changeFilesOnBranch(operations, options, branch);
      }
    }
  }

  async getChangeFileOperationsForBranch(
    files: { path: string; newPath?: string }[],
    branch: string,
  ) {
    const items: ChangeFileOperation[] = await Promise.all(
      files.map(async file => {
        const content = await result(
          file,
          'toBase64',
          partial(this.toBase64, (file as DataFile).raw),
        );
        let sha;
        let operation;
        let from_path;
        let path = trimStart(file.path, '/');
        try {
          sha = await this.getFileSha(file.path, { branch });
          operation = FileOperation.UPDATE;
          from_path = file.newPath && path;
          path = file.newPath ? trimStart(file.newPath, '/') : path;
        } catch {
          sha = undefined;
          operation = FileOperation.CREATE;
        }

        return {
          operation,
          content,
          path,
          from_path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    return items;
  }

  async changeFilesOnBranch(
    operations: ChangeFileOperation[],
    options: PersistOptions,
    branch: string,
  ) {
    return (await this.request(`${this.repoURL}/contents`, {
      method: 'POST',
      body: JSON.stringify({
        branch,
        files: operations,
        message: options.commitMessage,
      }),
    })) as FilesResponse;
  }

  /**
   * Get differences between two refs using Gitea's compare API
   */
  async getDifferences(
    baseBranch: string,
    headBranch: string,
  ): Promise<{ commits: GiteaCompareCommit[]; files: GiteaChangedFile[] }> {
    // Gitea compare endpoint: GET /repos/{owner}/{repo}/compare/{basehead}
    // For open authoring, retry since cross-repo comparisons may have eventual consistency delays
    const attempts = this.useOpenAuthoring ? 10 : 1;

    for (let i = 1; i <= attempts; i++) {
      try {
        const result: GiteaCompareResponse & { files?: GiteaChangedFile[] } = await this.request(
          `${this.originRepoURL}/compare/${encodeURIComponent(baseBranch)}...${encodeURIComponent(headBranch)}`,
        );

        return {
          commits: result.commits || [],
          files: result.files || [],
        };
      } catch (e) {
        if (i === attempts) {
          console.warn(`Reached maximum number of attempts '${attempts}' for getDifferences`);
          throw e;
        }
        // Exponential backoff
        await new Promise(resolve => setTimeout(resolve, i * 500));
      }
    }

    throw new APIError('Not Found', 404, API_NAME);
  }

  /**
   * Upload a blob to the repository
   */
  async uploadBlob(item: { raw?: string; sha?: string; toBase64?: () => Promise<string> }) {
    const contentBase64 = await result(
      item,
      'toBase64',
      partial(this.toBase64, item.raw as string),
    );
    const response: { sha: string } = await this.request(`${this.repoURL}/git/blobs`, {
      method: 'POST',
      body: JSON.stringify({
        content: contentBase64,
        encoding: 'base64',
      }),
    });
    item.sha = response.sha;
    return item;
  }

  /**
   * Create a new tree
   */
  async createTree(baseSha: string, tree: TreeEntry[]): Promise<{ sha: string }> {
    const result: { sha: string } = await this.request(`${this.repoURL}/git/trees`, {
      method: 'POST',
      body: JSON.stringify({ base_tree: baseSha, tree }),
    });
    return result;
  }

  /**
   * Update a tree with file changes
   */
  async updateTree(
    baseSha: string,
    files: { path: string; sha: string | null }[],
  ): Promise<{ sha: string; parentSha: string }> {
    const tree: TreeEntry[] = files.map(file => ({
      path: trimStart(file.path, '/'),
      mode: '100644',
      type: 'blob',
      sha: file.sha,
    }));

    const newTree = await this.createTree(baseSha, tree);
    return { ...newTree, parentSha: baseSha };
  }

  /**
   * Create a commit
   */
  async createCommit(
    message: string,
    treeSha: string,
    parents: string[],
    author?: { name: string; email: string; date?: string },
    committer?: { name: string; email: string; date?: string },
  ): Promise<{ sha: string }> {
    const result: { sha: string } = await this.request(`${this.repoURL}/git/commits`, {
      method: 'POST',
      body: JSON.stringify({ message, tree: treeSha, parents, author, committer }),
    });
    return result;
  }

  /**
   * Helper commit method that wraps createCommit
   */
  commit(message: string, changeTree: { parentSha?: string; sha: string }) {
    const parents = changeTree.parentSha ? [changeTree.parentSha] : [];
    return this.createCommit(message, changeTree.sha, parents);
  }

  /**
   * Update a branch reference to point to a new SHA
   */
  async patchBranch(
    branchName: string,
    sha: string,
    opts: { force?: boolean } = {},
  ): Promise<void> {
    const force = opts.force || false;
    // Gitea uses the same endpoint but with PATCH method
    await this.request(`${this.repoURL}/git/refs/heads/${encodeURIComponent(branchName)}`, {
      method: 'PATCH',
      body: JSON.stringify({ sha, force }),
    });
  }

  /**
   * Rebase a single commit onto a new base
   */
  async rebaseSingleCommit(
    baseCommit: { sha: string },
    commit: GiteaCompareCommit,
  ): Promise<{ sha: string }> {
    // Get the diff between the commit and its parent
    const parentSha = commit.parents[0]?.sha;
    if (!parentSha) {
      // No parent, just return the commit as is
      return { sha: commit.sha };
    }

    // Get the differences for this specific commit
    const result = await this.getDifferences(parentSha, commit.sha);
    const files = result.files || [];

    // If no files changed, return the base commit
    if (files.length === 0) {
      return baseCommit;
    }

    // For each changed file, we need to get its content from the commit
    // and create a new tree entry
    const treeUpdates: { path: string; sha: string | null }[] = [];

    for (const file of files) {
      if (file.status === 'removed') {
        treeUpdates.push({ path: file.filename, sha: null });
      } else {
        // Get the file SHA from the commit's tree
        try {
          const sha = await this.getFileSha(file.filename, {
            branch: commit.sha,
            repoURL: this.repoURL,
          });
          treeUpdates.push({ path: file.filename, sha });
        } catch (e) {
          console.warn(`Could not get SHA for file ${file.filename}`, e);
        }
      }

      // Handle renamed files
      if (file.status === 'renamed' && file.previous_filename) {
        treeUpdates.push({ path: file.previous_filename, sha: null });
      }
    }

    // Create a new tree based on the base commit with the diff applied
    const tree = await this.updateTree(baseCommit.sha, treeUpdates);

    // Create a new commit with the original message and author info
    const { message, author, committer } = commit.commit;
    const newCommit = await this.createCommit(
      message,
      tree.sha,
      [baseCommit.sha],
      author ? { name: author.name || '', email: author.email || '', date: author.date } : undefined,
      committer
        ? { name: committer.name || '', email: committer.email || '', date: committer.date }
        : undefined,
    );

    return newCommit;
  }

  /**
   * Rebase an array of commits one-by-one, starting from a given base SHA
   */
  async rebaseCommits(
    baseCommit: { sha: string },
    commits: GiteaCompareCommit[],
  ): Promise<{ sha: string }> {
    // If no commits or the first commit's parent already matches the base, return as is
    if (commits.length === 0) {
      return baseCommit;
    }

    if (commits[0].parents[0]?.sha === baseCommit.sha) {
      // Already rebased, return the last commit
      const head = commits[commits.length - 1];
      return { sha: head.sha };
    }

    // Re-create each commit over the new base
    let currentBase = baseCommit;
    for (const commit of commits) {
      currentBase = await this.rebaseSingleCommit(currentBase, commit);
    }

    return currentBase;
  }

  /**
   * Rebase a branch onto the default branch
   */
  async rebaseBranch(branch: string): Promise<{ sha: string }> {
    try {
      // Get the diff between the default branch and the editorial workflow branch
      const { commits } = await this.getDifferences(this.branch, branch);

      // Get the current head of the default branch as the base
      const defaultBranch = await this.getDefaultBranch();
      const baseCommit = { sha: defaultBranch.commit.id };

      // Rebase the commits onto the base
      const rebasedHead = await this.rebaseCommits(baseCommit, commits);

      return rebasedHead;
    } catch (error) {
      console.error('Error rebasing branch:', error);
      throw error;
    }
  }
}
